### ISSUE TITLE
Nginx support?

### ISSUE THREAD

**Issue by ronilaukkarinen** [gfwilliams/ThinGallery#1]
Nginx doesn't have automatic directories by default so this doesn't work as expected. Renaming to index.html doesn't display any photos.

**Comment by gfwilliams** [comment]
Do you have any suggestions for how to fix this?

Obviously it's not magic - if the server doesn't give any info about what's in directories there's not much it can do. Perhaps you have info about how to configure nginx?

Also, it says pretty clearly not to name it index in the README.

**Comment by ronilaukkarinen** [comment]
Just a thought, no suggestions. Yes, read the readme, but in nginx gallery.html was no dice. Built my own gallery for fast use, so this is no longer relevant. Sorry for bothering you.
