### ISSUE TITLE
Hide Parent Directory Folder

### ISSUE THREAD

**Issue by museion** [gfwilliams/ThinGallery#13]
Is there a way to hide the parent directory folder?  It becomes useless and would rather not have it.

**Comment by GaiusVampus** [comment]
I solved this with help by the Web server and simply added
IndexIgnore .. 
IndexIgnore gallery.html 
to .htaccess  for this directory (or the general web server configuration).

**Comment by gfwilliams** [comment]
I guess you mean the folder labelled `[BACK]`?

The `IndexIgnore` trick @GaiusVampus posted is really neat.

The gallery itself displays `[BACK]` if there's a link in the Index page that goes to a URL that's smaller than the current URL. If you're in the root of a webserver then you're fine, but obviously if you're in `/gallery` then that can be an issue. 

If you just wanted to mess with the file then you could do something with the code here to ignore URLs you didn't want: https://github.com/gfwilliams/ThinGallery/blob/master/gallery.html#L384

**Comment by museion** [comment]
Thanks @GaiusVampus that helped super quick. 


I do have one one more follow up question for non image types and displaying an predetermined image file, so going to close this one for me at least and open a new one if any of you are experts.  Super appreciate it!
