### ISSUE TITLE
Predetermined Image for Other Types of Files

### ISSUE THREAD

**Issue by museion** [gfwilliams/ThinGallery#14]
So I figured out how to add more files (like PSD) to appear in the gallery view by adding a new EXT (_ex: var EXT_OTHER_) at the top and referencing at the bottom to a Decimal Code that's pulled.  

But I wanted to make a custom Icon to appear so it's bigger in size like the others at 240px and represents the actual type of file it would be.  So I made a image file, but I'm unsure how to reference it below.  So I've got:

    _} else if (EXT_OTHER.indexOf(ext)>=0) {
      addBasicThumb(thumbs, href, "/images/icon.png");_

But of course that doesn't work, just an empty space.  Sorry I'm not a coder so don't know what I should be filling in to point to the icon image I'd want to use.

**Comment by gfwilliams** [comment]
Ahh - there's nothing in there at the moment that's do that, but you could replace `addBasicThumb` with something like:

```
function addBasicThumb(thumbs, href, iconText, imageURL) {
  var niceName = getNiceName(href);
  var im = document.createElement("DIV");
  im.innerHTML = imageURL ? '<div class="thumbimage" style="background-image:url('+imageURL+')"></div>' : '';
  im.innerHTML += '<div class="caption">'+decodeURIComponent(niceName)+'</div>';
  if (iconText) im.innerHTML += '<div class="thumbicon">'+iconText+'</div>';
  im.className = "thumb";
  im.setAttribute("href", href);
  im.onclick = function(e) {
    e.preventDefault();
    console.log("Clicked "+href);
    window.open(href, '_blank');
  };
  im = thumbs.appendChild(im);
}
```

Which adds an image background if it's supplied as a 4th argument. Then you could do something like:

```
} else if (EXT_OTHER.indexOf(ext)>=0) {
  addBasicThumb(thumbs, href, undefined, "/images/icon.png");
```

**OR** personally I'd just have a google around and try and find some emoji that fit with what you want for the file types, then copy the emoji's code into addBasicThumb as is done with the other uses of it.

**Comment by museion** [comment]
You are awesome.  This worked perfectly!
