### ISSUE TITLE
No image rotation

### ISSUE THREAD

**Issue by mbk87** [gfwilliams/ThinGallery#15]
Image thumbnail is rotating properly (data from EXIF).
When clicked on specific photo, it is not rotated.
When open real picture it is rotated properly (browser knows what to do)

**Comment by gfwilliams** [comment]
Please can you post an example picture and a screenshot? And what's your browser?

As I understand it, if you display any photo in the browser the browser should rotate it for you without having to get any data from EXIF, so the rotation only really needs to be applied to the thumbnail.

**Comment by mbk87** [comment]
https://bg.bz2.pl/sample/gallery.html
Browser: FF 68.0 (linux)
- loaded thumbnail: OK (rotated) [1]
- click on thumbnail: not OK (picture not rotated) [2]
- click on arrow in the bottom : OK (rotated) [3]
[1] https://imgur.com/OcQZou6
[2] https://imgur.com/Mrj4cFt
[3] https://imgur.com/Y3yM2CD

**Comment by gfwilliams** [comment]
Perfect, thanks! I get the same here.

**Comment by gfwilliams** [comment]
Try it now. The size is wrong because the browser scales it as if it's the other orientation, but my hacky solution to that didn't fix it totally so I've left that out. Maybe someone else would like to contribute a fix for that.
