### ISSUE TITLE
No thumbnails

### ISSUE THREAD

**Issue by gigajew** [gfwilliams/ThinGallery#18]
Thumbnails are never loading for me. Using apache2 on Ubuntu.

**Comment by gfwilliams** [comment]
I need more information - I have apache2 on ubuntu and it works great for me.

What Browser are you using? Does it work on other browsers?

Are there any messages in the Web Browser's developer console?

**Comment by GaiusVampus** [comment]
I assume you know what images files are in the directory together with gallery.html. You should be able to retrieve the image files directly with your browser. If not, the scripts within gallery.html can't load them as well. 
It would be helpful if you describe the "never loading" in more detail: Is the browser window completely black? Are filenames displayed but only the thumbnails are not displayed? Are they shown with an hour glass symbol?

**Comment by gigajew** [comment]
Ended up being a problem with permissions thanks
