### ISSUE TITLE
Page fails to render with filenames that resemble regex character ranges

### ISSUE THREAD

**Issue by dedworks** [gfwilliams/ThinGallery#24]
For example, create a file named "[BluRay-1080p].png"

The page fails to render the directory containing this file, with the following error in the javascript console:

```
Uncaught SyntaxError: invalid range in character class
    processIndexPage http://localhost:8000/gallery.html:419
    loadAllImages http://localhost:8000/gallery.html:461
    onload http://localhost:8000/gallery.html:528
    EventHandlerNonNull* http://localhost:8000/gallery.html:511
gallery.html:419:14
    processIndexPage http://localhost:8000/gallery.html:419
    (Async: EventHandlerNonNull)
    loadAllImages http://localhost:8000/gallery.html:461
    onload http://localhost:8000/gallery.html:528
    (Async: EventHandlerNonNull)
    <anonymous> http://localhost:8000/gallery.html:511
```

I didn't dig into the source but presumably the unescaped filename is being passed raw to a regex parser, where [y-1] is not a valid character range...

**Comment by gfwilliams** [comment]
Thanks for the report - just looked and this PR added the unescaped regex :( 

https://github.com/gfwilliams/ThinGallery/pull/8

I've just replaced it with a simple "string.includes" check which it should have been from the start.

**Comment by dedworks** [comment]
Thanks, that was quick! It's working in the latest version for me now.
