### ISSUE TITLE
Show videos with an icon and no thumbnail

### ISSUE THREAD

**Issue by 0x0f0f0f** [gfwilliams/ThinGallery#9]
Might be a great improvement.

**Comment by 0x0f0f0f** [comment]
Yeah it would be fine. Also opening it in the slideshow may look better.
What about also editing the three icons in the slideshow? The "open file" arrow gets really small on desktop.

**Comment by gfwilliams** [comment]
Do you have an example of the icons? They seem fine (if not a bit too big) on my desktop
